### ISSUE TITLE
Provide Node Icons

### ISSUE THREAD

**Issue by moethu** [tt-acm/DynamoForRebar#10]
Node Icons need to be provided.

**Comment by ksobon** [comment]
@bhowes-tt @moethu let me know if you need working examples on how to add icons. I understand that Dynamo team has a little bit of an issue with the documentation. 

Ps. @moethu the underscores that were added is due to "strongly typed" resource file. Just clear the CustomTool property of *.resx. I think that worked for me.

**Comment by moethu** [comment]
Hi @ksobon,
yes we figured that out but the problem is that even with correct named icons (namespace) including dots - dynamo shows blank images. Do you have any idea on this?
I followed this one: https://github.com/DynamoDS/Dynamo/wiki/Add-Icons-for-a-Zero-Touch-Assembly

**Comment by moethu** [comment]
![2015-09-15_15h21_56](https://cloud.githubusercontent.com/assets/8201465/9879029/82855dcc-5bbd-11e5-975c-1bef9d39f5d4.png)

**Comment by ksobon** [comment]
@moethu First thing that I noticed was a wrong name of your resources:

![untitled-1](https://cloud.githubusercontent.com/assets/529781/9879907/5c72c80c-5b97-11e5-9a6a-7f2bf02cfe47.png)

I was also looking at your *.csroj file and didnt see the required modifications for the target:

![image](https://cloud.githubusercontent.com/assets/529781/9879943/8eafe728-5b97-11e5-9b45-ac18a626cba8.png)

Try cleaning that up and let me know if this helps.

**Comment by moethu** [comment]
@ksobon , the Icons provided for testing are regarding a different namespace (see Revit.Elements.Tag). Sadly that's not the issue.
![2015-09-15_16h45_09](https://cloud.githubusercontent.com/assets/8201465/9881712/226cb3ca-5bc9-11e5-86f0-e191f24745ab.png)

**Comment by moethu** [comment]
![2015-09-15_16h45_09](https://cloud.githubusercontent.com/assets/8201465/9881870/c5b386e4-5bc9-11e5-8e28-65e45914af5d.png)

**Comment by moethu** [comment]
This time I compiled a library with various naming options but not even one of them worked out.
![2015-09-15_17h00_23](https://cloud.githubusercontent.com/assets/8201465/9882576/39fb2cc0-5bcd-11e5-9d22-5332be7ffdac.png)

**Comment by ksobon** [comment]
You must be missing something because I got one of them to work on mine:

![untitled-1](https://cloud.githubusercontent.com/assets/529781/9891356/b3375900-5bd3-11e5-95eb-966c4314ea2a.jpg)

I will make a pull request for the files that i changed to make this work.

**Comment by moethu** [comment]
Hi, good to see them working on your side. Sadly, it doesn't work on my machine. The customization library has been loaded but the result are blank icons instead of the standard Dynamo Icon:
![2015-09-16_08h47_52](https://cloud.githubusercontent.com/assets/8201465/9899152/d8740c1e-5c4f-11e5-9155-f0a9826413d2.png)
I will try this on a different machine. One thing I noticed, on your screenshot it says No Description available, which is strange because there is a xml summary for every method.

**Comment by ksobon** [comment]
agrrr. this is weird. i will investigate further.

**Comment by moethu** [comment]
Thanks, I will test it on a different machine.

**Comment by ksobon** [comment]
can you just try these two DLLs? if they work then the problem must be associated with something about how it gets compiled on your machine. also, let's chat  ksobon1986@gmail.com maybe a quick screen share can help you reproduce my steps and we will see if you can get it work. Then we can tackle the disappearing description problem. 

ps. Attachment is a ZIP file that I changed an extension to JPG.
![bin](https://cloud.githubusercontent.com/assets/529781/9907807/d0fa2d24-5c5e-11e5-84f3-ba334349da0f.jpg)

**Comment by moethu** [comment]
Thanks, just dropped the Idea of creating a separate project for the Images and added them to the Rebar Project itself like Autodesk recommends in the documentation. This way its working fine. Just got to draw some more Icons now.
