### ISSUE TITLE
Testing framework

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/DynamoForRebar#26]
Set up a RTF project in this solution that runs system tests on the package's sample files.  Today's release of Dynamo 0.8.2 seems like as good a reason as any to lace this up!

Have a look at the Energy Analysis or Dynamo SAP project for a precedent.

**Comment by moethu** [comment]
Implemented in the DynamoRebarTest Project

**Comment by moethu** [comment]
![2015-09-15_11h37_46](https://cloud.githubusercontent.com/assets/8201465/9874522/59c99930-5b9e-11e5-89ff-9434ec4b5ff4.png)
