### ISSUE TITLE
Revit stops working when using slider for number of curves

### ISSUE THREAD

**Issue by tjordaske** [tt-acm/DynamoForRebar#28]
I've created the same nodes as showed in http://core.thorntontomasetti.com/dynamo-for-rebar-is-now-available/
But in stead of using a 'number' node for the number of curves I've used a 'number slider' node. When Dynamo is running automatically I get a fatal error when changing the number slider.

**Comment by moethu** [comment]
Thanks for reporting this. Actually I got the same issue once I switch to Auto in general.
I will have a look at this issue. Nevertheless I can't recommend using the Auto mode in combination with the Rebar nodes since they are acting quite slow.

**Comment by moethu** [comment]
The issue only appears when using the RebarContainer, single Rebar, and Tags are acting fine.
Dynamo gets stuck because it continuously tries to create a RebarContainer.

**Comment by tjordaske** [comment]
Thanks for the response! ☺

Is it possible to add stirrups to a beam with variable height using Dynamo?

Met vriendelijke groeten,
Kind regards,
Meilleures salutations,

Joris Van Bossche
Application Consultant BIM
joris.vanbossche@i-theses.com<mailto:joris.vanbossche@i-theses.com>
Twitter: @RevitAdvisor<https://twitter.com/RevitAdvisor>

[cid:image001.jpg@01D0E65B.04B668A0]<http://i-theses.com/nl/events/seminaries/4380-di-22-09-parametrisch-ontwerpen-met-dynamo>

[cid:image002.jpg@01D0E65B.04B668A0]<http://i-theses.com/nl/events/seminaries/4383-di-13-10-advance-steel-in-combinatie-met-revit>


Van: moethu [mailto:notifications@github.com]
Verzonden: dinsdag 15 september 2015 11:26
Aan: tt-acm/DynamoForRebar <DynamoForRebar@noreply.github.com>
CC: Joris Van Bossche <joris.vanbossche@i-theses.com>
Onderwerp: Re: [DynamoForRebar] Revit stops working when using slider for number of curves (#28)


The issue only appears when using the RebarContainer, single Rebar, and Tags are acting fine.
Dynamo gets stuck because it continuously tries to create a RebarContainer.

**Comment by moethu** [comment]
Hi, it should be possible. Didn't have much time testing it but you should just provide the section geometry like this:
![2015-09-15_15h04_36](https://cloud.githubusercontent.com/assets/8201465/9878622/957c7e9e-5bbb-11e5-8afc-8b36d8531a47.png)
