### ISSUE TITLE
Revit 2016, rebars are created miles away from host

### ISSUE THREAD

**Issue by jbenoit44** [tt-acm/DynamoForRebar#29]
I've used the following surface sample file. rebars from curve or container are created, but far far away from the host.
![image](https://cloud.githubusercontent.com/assets/4572196/9879223/b36cebc2-5bc6-11e5-9385-f5355ac63ec9.png)
The result vary depending on the project units. best result is centimeters.
![image](https://cloud.githubusercontent.com/assets/4572196/9879251/d60023f2-5bc6-11e5-8d73-f0c8b1779b87.png)
worth mentioning project was created from French template

**Comment by moethu** [comment]
Hi @jbenoit44 , thanks for your feedback.
yes, the offset values etc. are depending on your Revit Project Units. In the sample files there is an offset from surface defined. I have been working in a file based on mm.
What is your offset value?

**Comment by jbenoit44** [comment]
Ok, tried again and seems fine now. will do further testing. thanks.
