### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by TheCleaner101** [tt-acm/DynamoForRebar#31]
I keep getting: Warning: RebarContainer.ByCurve operation failed. 
An internal error has occurred.

I am using Revit 2016 with Dynamo 8.2...
Just installed 0.8.0 and tried again but still got an internal error from both rebar container and single rebar.

**Comment by moethu** [comment]
Thank you for your feedback, the "internal error" is thrown by the actual Revit Rebar API method. Mostly this means Revit cannot handle your input geometry, how does your geometry look like?

**Comment by TheCleaner101** [comment]
Thanks for all the effort moethu. 
I have been trying the nodes on a simple structural wall. I've attached an image.
![image](https://cloud.githubusercontent.com/assets/11429528/9936570/8d9609a8-5d54-11e5-8470-34fbaa8fb8b2.png)

**Comment by moethu** [comment]
Hi there, Revits Rebar API seems to have problems with bars with different Z values.

**Comment by moethu** [comment]
#38
