### ISSUE TITLE
No influence of FollowingSurface offset paramater on curvature

### ISSUE THREAD

**Issue by dietervermeulen** [tt-acm/DynamoForRebar#37]
Hi, it seems that applying the Offset value on the Rebar.FollowingSurface node doesn't influence the radius of a curve when applying on a single curved wall. In an earlier post I read that offset might be interpreted as cover (?). If that is the plan, then this should not just shift the rebar lines with the offset value, but it should change the radius of the rebar lines instead. If not you will get the effect as below, where the rebar objects are not concentric with the wall radius.

If the offset is not intended to be seen as "cover", how can you get then the rebar objects concentric with the curved wall?

![image](https://cloud.githubusercontent.com/assets/12096185/10146960/b792add0-662b-11e5-8460-9c8b9c9726d4.png)

**Comment by moethu** [comment]
I so far assumed the internal Geometry Translate method would handle that.
The GetPerimeterCurves Method doesn't distinguish between Arcs and Lines.

**Comment by dietervermeulen** [comment]
The Curve.Offset method is translating and changing radius. The Translate keeps the original shape.

**Comment by moethu** [comment]
Thanks, changed to Offset

**Comment by dietervermeulen** [comment]
Seems still the same problem in v 1.7...

**Comment by moethu** [comment]
Hi, changed it to offset though in v1.6

**Comment by moethu** [comment]
Sorry, embarrassing... I didn't change it. update coming now.

**Comment by moethu** [comment]
please try 1.8

**Comment by dietervermeulen** [comment]
Works fine in 1.8 !
![image](https://cloud.githubusercontent.com/assets/12096185/10535667/fac81858-73e4-11e5-830e-5778c09944ae.png)
