### ISSUE TITLE
Set Rebar Hook Type to "none"

### ISSUE THREAD

**Issue by dietervermeulen** [tt-acm/DynamoForRebar#39]
I miss a setting where I can choose "None" for the Rebar Hook Type. Not all rebars need to have hooks at the ends.

**Comment by moethu** [comment]
Hi Dieter, you would have to load a Hook Type that is called None and doesn't contain anything.

**Comment by dietervermeulen** [comment]
You can not make that kind of Hook Type in Revit. None is a setting in the parameters of a Rebar once modelled. A hook type needs a multiplier of at least 0.01 and the angle can't be 0. 
So that would not solve the problem.

**Comment by moethu** [comment]
The problem is the API is really picky about null values. I'm trying some kind of workaround

**Comment by moethu** [comment]
Just published v.1.6 with a bool toggle for noHooks

**Comment by moethu** [comment]
Sadly I cannot provide a None option at the moment in the drop down - because I would have to handle all the null values internally first

**Comment by moethu** [comment]
Got it fixed now, you can easily select None

**Comment by moethu** [comment]
v 1.7
