### ISSUE TITLE
"View as Solid" / "View unobscured" toggles

### ISSUE THREAD

**Issue by dietervermeulen** [tt-acm/DynamoForRebar#42]
Suggestion as improvement: it would be great having an option to toggle the "View Visibility State" of the generated rebars. This because of if you set it once for your bars, and change the number of bars with your Dynamo script, then the "View Vis State" change back to "unchecked". See screenshot below.

![image](https://cloud.githubusercontent.com/assets/12096185/10308262/c34eff70-6c34-11e5-877c-4ad97c979552.png)

**Comment by vasshaug** [comment]
This would be pretty nifty to control as a Project or Revit setting Dieter. Has been a request on Pawel's desk for 5 year:)

**Comment by dietervermeulen** [comment]
Well it works on API level. Sofistik managed to toggle it. Not sure we should control it in Revit or project. On element basis, would be effective already.

**Comment by vasshaug** [comment]
It would work very well on element basis if some person could make View as solid on byDefault. I have never understood why anyone would ever want to see pixel rebars in Fine Detail Level.

**Comment by moethu** [comment]
Good point, maybe we should have an entire visibility control library for Elements in Dynamo?

**Comment by moethu** [comment]
@dietervermeulen , Visibility Nodes added:
![2015-11-03_08h47_01](https://cloud.githubusercontent.com/assets/8201465/10903994/7605c5bc-8207-11e5-92ac-6f5b1b224dba.png)

**Comment by MDCnerd97** [comment]
are the nodes in your previous comment availiable somewhere?  are they with a particular package?  would really love to be able to change the view settings of my rebars.

**Comment by moethu** [comment]
@MDCnerd97 yes they are part of this Package, just search for rebar in the dynamo pkg manager.

**Comment by MDCnerd97** [comment]
Dear sir,

Thank you for your response!  If I might trouble you for one last question.  I have my graph setup using the node previously discussed (see attachment), but I’m getting an error with the 3d view selection.  How should I go about telling it to change the view style for all 3d views?  Any and all help is appreciated.  Thank you for your time and I look forward to your reply.

Sincerely,

Mike Tuter
Engineering Design Technician
Design & Development Division
Missouri Department of Conservation
(573) 522-4115 ext. 3743
(573) 522-2020 (fax)
mike.tuter@mdc.mo.gov<mailto:mike.tuter@mdc.mo.gov>

**Comment by moethu** [comment]
@MDCnerd97 could you attach the image on github please, I cannot see email attachments here.

**Comment by MDCnerd97** [comment]
@moethu absolutely.  Sorry for the confusion, here is my previous email response with the image attached.  Thank you again for your help.

Dear sir,

Thank you for your response!  If I might trouble you for one last question.  I have my graph setup using the node previously discussed (see attachment), but I’m getting an error with the 3d view selection.  How should I go about telling it to change the view style for all 3d views?  Any and all help is appreciated.  Thank you for your time and I look forward to your reply.

**Comment by MDCnerd97** [comment]
![dynamo graph](https://cloud.githubusercontent.com/assets/16823398/12550992/d4656192-c32c-11e5-8bdc-a31021cfb4cf.png)

**Comment by MDCnerd97** [comment]
@moethu sorry, didn't get the image attached the first time.

**Comment by moethu** [comment]
@MDCnerd97 , the Rebar SetSolidInView Node requires a Rebar as an input, not a Rebar Bar Type.
Either create a Bar or Container in Dynamo or use Select Model Element to select an existing Rebar

**Comment by MDCnerd97** [comment]
@moethu , Thank you again for your assistance.  I hate to ask again, but it says i have a problem with the 3d view i have chosen.  the node says it does not recognize an "axonometricView".  is there another node i should be using to select the correct view.  I have attached my revised graph.  Thank you again for your help, I do appreciate it.
![dynamo graph-2](https://cloud.githubusercontent.com/assets/16823398/12563637/e0cbf4de-c370-11e5-861b-5d44f2ad2d11.png)

**Comment by moethu** [comment]
@MDCnerd97 you did everything correctly. I guess the Revit API doesn't allow setting a 3D View here. I checked the code and I'm not manipulating the incoming view - so the error is thrown by the Revit API. If I'm setting it manually in Revit it also works for 3D Views. I'll look more into this. Thanks.
