### ISSUE TITLE
Following Surface on Trapezoidal surfaces

### ISSUE THREAD

**Issue by dietervermeulen** [tt-acm/DynamoForRebar#44]
When working with the Rebar.FollowingSurface on a trapezoidal surface, I would expect the lines getting trimmed at the surface edge, which is not yet done. See screenshot below.

![image](https://cloud.githubusercontent.com/assets/12096185/10312072/e75d0744-6c49-11e5-8188-f9fdd2f7f108.png)

**Comment by moethu** [comment]
@dietervermeulen ,
they do if you set the idealize property to false.
This is the standard U,V parametrization from Autodesk. The non idealized is a solution I came up with to fix that.

**Comment by dietervermeulen** [comment]
Seems to be solved in Dynamo 0.9 with the Rebar 0.2 package. Lines are trimmed by default now, and the idealize = true will even do the reverse now :-)
