### ISSUE TITLE
Rebars not generating in build 0.9

### ISSUE THREAD

**Issue by aminghali** [tt-acm/DynamoForRebar#45]
I upgraded to daily build 0.9 and somehow rebars won't generate. Just showing blue lines in the revit model
![1234](https://cloud.githubusercontent.com/assets/6287630/10316431/486708e8-6c70-11e5-91e2-91cacf862a64.png)
![123](https://cloud.githubusercontent.com/assets/6287630/10316432/4867281e-6c70-11e5-929f-8a6412265857.png)

**Comment by moethu** [comment]
Hi @aminghali , haven't built 0.9 yet. Will do so asap.

**Comment by moethu** [comment]
Hi @aminghali , We can't provide binaries for pre-releases, which 0.9 still is. But you can build it yourself.

**Comment by aminghali** [comment]
Which build do I need to have to get it to work. Thanks for a great tool by
the way.

On Tuesday, October 6, 2015, moethu <notifications@github.com> wrote:

> Closed #45 <https://github.com/tt-acm/DynamoForRebar/issues/45>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tt-acm/DynamoForRebar/issues/45#event-428259143>.
>


-- 
Amin

**Comment by moethu** [comment]
The current release 8.2 (http://dyn-builds-data.s3-us-west-2.amazonaws.com/DynamoInstall0.8.2.exe)

**Comment by aminghali** [comment]
I reverted back to the 0.8.2 but the drop down menus are missing and it's
not working. Can you help ?
[image: Inline image 1]

Amin

**Comment by aminghali** [comment]
Thank you, worked great.
