### ISSUE TITLE
RebarContainer by Bars creates new rebars

### ISSUE THREAD

**Issue by dietervermeulen** [tt-acm/DynamoForRebar#57]
When creating single rebars with the Rebar.ByCurve function, you get single Rebar objects in Revit. When you connect its output to the RebarContainer.byBars node, in order to get them grouped in a Rebar "set", then it creates a NEW set of grouped rebars on top of the previously single ones, while the single ones should be replaced by the grouped rebar.

(tested in Dynamo 0.8.2 with package 0.1.8)

![image](https://cloud.githubusercontent.com/assets/12096185/10840602/3adaf83c-7ee1-11e5-8d76-adc36e4c6d4e.png)

**Comment by moethu** [comment]
fixed.
