### ISSUE TITLE
Element binding : Changes to script, makes new rebars

### ISSUE THREAD

**Issue by dietervermeulen** [tt-acm/DynamoForRebar#58]
When you make changes to the script, which doesn't influence the topology of the rebar cage, then the package seems to recreate the rebars in Revit. 
Possible changes: changing spacing, diameter, number of bars, ...

This invokes that you have to rework the objects (ie visibility, tagging, ...)

**Comment by moethu** [comment]
Hi Dieter, sadly I cannot do much about it. I can only update few properties using the Rebar API. If there is any Style or Geometry change I got to delete and create a new Rebar Element.

**Comment by moethu** [comment]
Scan for Geometry Changes first

**Comment by moethu** [comment]
fixed.
