### ISSUE TITLE
Mulitline text parameter appears as single line

### ISSUE THREAD

**Issue by nmeek** [tt-acm/DynamoForRebar#59]
Using Element.SetParameterByName for a multi-line text parameter results in a single line of text, even though the string contains carriage returns (using '\n' or '\r')

**Comment by moethu** [comment]
Hi @nmeek , not sure what you are referring to, could you explain that in more detail please?
Element.SetParameterByName is not part of the DynamoForRebar Repo.

**Comment by nmeek** [comment]
In Revit, you can create a parameter with a "Multiline Text" data type. 
![multiline text](https://cloud.githubusercontent.com/assets/15450035/10856352/2ef0b802-7f15-11e5-902d-98586d9b050b.PNG)
However, when setting this parameter, all lines of the string are concatenated to one line.
![dynamo multiline text](https://cloud.githubusercontent.com/assets/15450035/10856700/6cc252ec-7f17-11e5-8363-525389b74b8d.PNG)
![multiline text result](https://cloud.githubusercontent.com/assets/15450035/10856706/77b821f4-7f17-11e5-9164-2eb020c9beb8.PNG)

**Comment by moethu** [comment]
thanks for reporting this. Could you please post that in the DynamoDS Revit Repo? Dynamo For Rebar doesn't implement the Node you would like to get fixed. Therefore I cannot fix this issue.
