### ISSUE TITLE
Element Material Properties

### ISSUE THREAD

**Issue by nmeek** [tt-acm/DynamoForRebar#60]
Please provide access to the hosting element's material and its properties (Identity, appearance, physical...)

**Comment by moethu** [comment]
@nmeek , isn't there any node for querying material properties of elements yet in the Dynamo Revit Library? I Didn't check.

**Comment by nmeek** [comment]
I couldn't find one.

**Comment by moethu** [comment]
https://core-studio.gitbooks.io/dynamoforrebar/content/material_properties.html

published a new version containing Nodes for Material Properties
