### ISSUE TITLE
RebarStyle.ByName output wrong?

### ISSUE THREAD

**Issue by dietervermeulen** [tt-acm/DynamoForRebar#71]
![image](https://cloud.githubusercontent.com/assets/12096185/16036545/bb016e80-321c-11e6-8645-458214decc42.png)
I want to reuse the same rebar style from a selected rebar object. Using the GetParameter.ByName on the rebar object and searching for "Style" returns "0" or "1". This could be translated into "Standard" or "Stirrup/Tie" and then be ported through RebarStyle.ByName to reuse this in the Rebar.ByCurve creation method. Though this last one doesn't accept the input from RebarStyle.ByName. It is not an array problem if you ask me, as it works if you would use the RebarStyle drop down node. Any advise?

**Comment by dietervermeulen** [comment]
Same problem by the way with the "RebarHookOrientation.ByName". Inputting a string value returns the rebar hookorientation well, but is not usable in the Rebar.ByCurve node.

**Comment by moethu** [comment]
fixed this with a toString node
