### ISSUE TITLE
package is not updated for dynamo 2.0

### ISSUE THREAD

**Issue by mjkkirschner** [tt-acm/DynamoForRebar#76]
any takers? :)

**Comment by mjkkirschner** [comment]
this might come in handy:
https://github.com/DynamoDS/Dynamo/wiki/Update-Packages-from-1.3-to-2.0

**Comment by moethu** [comment]
@mjkkirschner thanks, I just updated my UI nodes but they are no longer showing up if I put the dll into ProgramFiles/Dynamo/Dynamo Revit/2/Revit_2018/nodes
Do I have to put them somewhere else?

**Comment by mjkkirschner** [comment]
I recommend referencing the same version of json.net as Dynamo and Revit do - json.net 8.03 (potentially your dlls are failing to load because of the reference to the newer json.net)

**Comment by mjkkirschner** [comment]
I believe this is noted here:
https://github.com/DynamoDS/Dynamo/wiki/Update-Packages-from-1.3-to-2.0#general-packaging-rules

also we should now have a dep on this package version of json.net in the dynamo nuget packges.

**Comment by moethu** [comment]
@mjkkirschner thanks, I downgraded to 803 but they are still not showing up. Did you change anything regarding the UI nodes location?

**Comment by mjkkirschner** [comment]
Ah, yes this is happening because of some changes to the library @racel - you'll need to test your UI nodes in your package.

**Comment by moethu** [comment]
@mjkkirschner I moved my UI dlls to the package dir in AppData,
and adapted the implementation to https://github.com/DynamoDS/DynamoRevit/blob/8e254612f9be6bdf72cb4a04a6de746ea31c6aa4/src/Libraries/RevitNodesUI/GenericClasses.cs
and https://github.com/DynamoDS/DynamoRevit/blob/8e254612f9be6bdf72cb4a04a6de746ea31c6aa4/src/Libraries/RevitNodesUI/RevitTypes.cs
But the UI dll doesn't show up in Dynamo. Nothing in console logs.

**Comment by mjkkirschner** [comment]
I'm not clear where your dlls are - are they located in an actual packages's bin folder, that contains a package.json file that marks them as node libraries?

can you share an image of your package directory and package.json file - do other nodes in your package load?

**Comment by moethu** [comment]
pkg.json
```
{"license":"","file_hash":null,"name":"Dynamo for Rebar","version":"1.2.0","description":"A Dynamo package for authoring geometrically complex rebar models in Revit 2016.","group":"","keywords":["rebar"],"dependencies":[],"contents":"","engine_version":"1.2.1.2854","engine":"dynamo","engine_metadata":"","site_url":"http://core.thorntontomasetti.com/dynamo-for-rebar-is-now-available/","repository_url":"https://github.com/tt-acm/DynamoForRebar","contains_binaries":true,"node_libraries":["DynamoRebar, Version=0.3.1.0, Culture=neutral, PublicKeyToken=null","DynamoRebarUI.customization, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","DynamoRebarUI, Version=0.3.0.0, Culture=neutral, PublicKeyToken=null","DynamoRebar.customization, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"]}
```
Versions are fine too.
![image](https://user-images.githubusercontent.com/8201465/42275605-b2042cb4-7f45-11e8-82c2-5b416dfec6e4.png)

**Comment by mjkkirschner** [comment]
I'm not sure the customization dll(icons?) should be marked as a node library... but not sure that would cause any issues.

some stuff to check:
* any errors in the console or notifications in the dynamo notifications panel?
* do you have any paths in the manage package paths menu item ( in dynamo 2.0 when you import a dll directly it adds the path directly to the manage package paths directory).

otherwise can try to build and see if I can reproduce.

**Comment by eertugrul** [comment]
should work now, @moethu  please close the issue if this was already taken care. thnks
