### ISSUE TITLE
ComputeDrawingCurves()

### ISSUE THREAD

**Issue by gaborschnierer** [tt-acm/DynamoForRebar#77]
hi moethu

Thanks for your contributions for keeping the project updated!
Do you have any ideas about this error message?

Warning: Rebar.ByCurve operation failed.
Method not found:
'System.Collection.Generic.IList 1<Autodesk.Revit.DB.Curve>
Autodesk.Revit.DB.Structure.Rebar.ComputedrawingCurves()'.

Clue: I'm using Revit 2019
[ObsoleteAttribute("This method is deprecated in Revit 2018 and will be removed in a future version. Use GetShapeDrivenAccessor().ComputeDrivingCurves() instead.")]
http://www.revitapidocs.com/2018.1/cc949899-f482-635c-75e9-2924acdd4c6a.htm

![image](https://user-images.githubusercontent.com/30599750/43061779-d544878a-8e56-11e8-975e-2918ac05c47c.png)

**Comment by moethu** [comment]
thanks @gaborschnierer , already fixed that with this commit: https://github.com/tt-acm/DynamoForRebar/commit/b2bbd51e6ba728c6f27ef9b4ea0e869909898dcc
however the package hasn't been updated yet.
In the meantime please pull the binary directly from this repo:
https://github.com/tt-acm/DynamoForRebar/blob/master/DynamoRebar.dll?raw=true
and replace the one in your package.

**Comment by gaborschnierer** [comment]
Awesome, you're great!
I'm about to leave for a week of vacation to Italy, no rebar till I'm back. Maybe the package gets updated in the meantime, so I can spare the binary.
Thanks again!
