### ISSUE TITLE
Release Package again

### ISSUE THREAD

**Issue by moethu** [tt-acm/DynamoForRebar#78]
@eertugrul I updated the package the other day - missed an API change.
COuld you release it again please?

**Comment by eertugrul** [comment]
@moethu i don't have Revit 2019 yet, u meant u corrected changes related to R2019 ?
I released latest package with R2018 and Dynamo 2 versions

**Comment by moethu** [comment]
@eertugrul that's fine you can release it with R2018 as well

**Comment by moethu** [comment]
@eertugrul ? still around?

**Comment by eertugrul** [comment]
v 2.0.1 released today
