### ISSUE TITLE
Release DynamoForRebar package

### ISSUE THREAD

**Issue by moethu** [tt-acm/DynamoForRebar#81]
Release Notes:

* Fixed:
	* Unit conversion for diameters (units are now converted automatically)
	* Set solid/unobscured nodes are now working with rebar selected from revit documents
* Added: 
	* Create freeform rebar from curves
	* Create rebar sets directly in dynamo using the new SetLayout components
	* Get properties of rebar sets

**Comment by moethu** [comment]
@eertugrul would you do me a favour and release it one more time? You can use the above release notes for the CORE blog

**Comment by eertugrul** [comment]
thanks
